extends: airbnb
env:
    browser: true
    node: true
parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
rules:
    indent: [error, 4]
    react/jsx-indent: [error, 4]
    react/jsx-indent-props: [error, 4]
